name: run tests
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
          cache-dependency-path: 'src/pnpm-lock.yaml'
      - name: Build
        working-directory: src/frontend
        run: |
          pnpm install
          pnpm build

  build-browser-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
          cache-dependency-path: 'src/pnpm-lock.yaml'
      - name: Build
        working-directory: src/browser-extension
        run: |
          pnpm install
          pnpm run zip

  test-backend:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
          cache-dependency-path: 'src/backend/poetry.lock'
      - name: Test
        working-directory: src/backend
        env:
          AZURE_ENDPOINTS: ${{ secrets.AZURE_ENDPOINTS }}
          AZURE_API_KEYS: ${{ secrets.AZURE_API_KEYS }}
          AZURE_MODEL_DEPLOYMENTS: ${{ secrets.AZURE_MODEL_DEPLOYMENTS }}
          AZURE_DOC_INTELLIGENCE_ENDPOINT: ${{ secrets.AZURE_DOC_INTELLIGENCE_ENDPOINT }}
          AZURE_DOC_INTELLIGENCE_KEY: ${{ secrets.AZURE_DOC_INTELLIGENCE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SECRET_ENCRYPTION_KEY: ${{ secrets.SECRET_ENCRYPTION_KEY }}
        run: |
          poetry install
          poetry run pyright
          cp ../sample.env ../../.env
          poetry run alembic revision
          poetry run pytest

  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
          cache-dependency-path: 'docs/pnpm-lock.yaml'
      - name: Publish
        run: .github/gh-pages-deploy.sh
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
